# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v3-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn -s .circleci.settings.xml deploy -DAWS_DEFAULT_REGION=us-east-1

      - run:
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            curl 'https://mminella-data-flow-server.apps.pcfone.io/tasks/schedules/devnexus-schedule' -i -X DELETE
            cf api https://api.run.pcfone.io
            echo $CF_USERNAME
            echo $cf_username
            cf auth $cf_username $cf_password
            cf target -o pivot-mminella -s playground
            cf delete devnexus-job -f
            curl 'https://mminella-data-flow-server.apps.pcfone.io/tasks/schedules' -i -X POST -d 'scheduleName=devnexus-schedule&taskDefinitionName=devnexus-job&properties=scheduler.cron.expression%3D*%2F1%20*%20%3F%20*%20*'
